// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMsayuxxVkNMcVpBSj9BYOCMNH9C4MJbc',
    appId: '1:393812680043:web:cb310a62143c22ba88c02e',
    messagingSenderId: '393812680043',
    projectId: 'quizzie-flutter',
    authDomain: 'quizzie-flutter.firebaseapp.com',
    storageBucket: 'quizzie-flutter.firebasestorage.app',
    measurementId: 'G-NXEPQ505SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRIhb2Ds1tz2UUsFEL45KQhlSeeCVhPY',
    appId: '1:393812680043:android:710540d383df75b188c02e',
    messagingSenderId: '393812680043',
    projectId: 'quizzie-flutter',
    storageBucket: 'quizzie-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZTWjQA-NQjvc096os3rMcJFPAAhZJUU',
    appId: '1:393812680043:ios:528c8d52570ed3a588c02e',
    messagingSenderId: '393812680043',
    projectId: 'quizzie-flutter',
    storageBucket: 'quizzie-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeZTWjQA-NQjvc096os3rMcJFPAAhZJUU',
    appId: '1:393812680043:ios:528c8d52570ed3a588c02e',
    messagingSenderId: '393812680043',
    projectId: 'quizzie-flutter',
    storageBucket: 'quizzie-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMsayuxxVkNMcVpBSj9BYOCMNH9C4MJbc',
    appId: '1:393812680043:web:677835bb7d36dbd688c02e',
    messagingSenderId: '393812680043',
    projectId: 'quizzie-flutter',
    authDomain: 'quizzie-flutter.firebaseapp.com',
    storageBucket: 'quizzie-flutter.firebasestorage.app',
    measurementId: 'G-7KGX7BCB4J',
  );
}
